- name: Install tar gzip
  become: yes
  apt:
    name: ["tar", "gzip"]
    state: latest

- name: Install nodejs
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: Install n to special node version
  become: yes
  npm:
    name: n
    global: yes

- name: Install nodejs 13.8.0
  become: yes
  shell: n 13.8.0

- name: Install pm2
  become: yes
  npm: 
    name: pm2
    global: yes