- name: Add environment to ec2
  shell: |
    echo "TYPEORM_CONNECTION=${TYPEORM_CONNECTION}"
    echo "export TYPEORM_CONNECTION=${TYPEORM_CONNECTION}" >> /home/ubuntu/.profile
    echo "export TYPEORM_ENTITIES=${TYPEORM_ENTITIES}" >> /home/ubuntu/.profile
    echo "export TYPEORM_HOST=${TYPEORM_HOST}" >> /home/ubuntu/.profile
    echo "export TYPEORM_PORT=${TYPEORM_PORT}" >> /home/ubuntu/.profile
    echo "export TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> /home/ubuntu/.profile
    echo "export TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> /home/ubuntu/.profile
    echo "export TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> /home/ubuntu/.profile
    echo "export TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}" >> /home/ubuntu/.profile
    echo "export TYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR}" >> /home/ubuntu/.profile
    
- name: "Update apt packages"
  apt:
    upgrade: yes
    update_cache: yes

- name: Install nodejs and dependencies
  apt:
    name: ["nodejs", "npm", "tar", "gzip"]
    state: latest

- name: Install n to special node version
  npm:
    name: n
    global: yes

- name: Install nodejs 13.8.0
  shell: n 13.8.0

- name: Install pm2
  npm: 
    name: pm2
    global: yes