- name: Copy backend
  become: yes
  copy:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/udapeople/
- name: Extract Backend
  become: yes
  shell: |
    apt install tar gzip
    cd /home/ubuntu/udapeople
    tar -xf artifact.tar.gz
    ls
# - name: Start server
#   shell: |
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
#     export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
#     [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
#     nvm install 13.8.0
#     npm install -g pm2
#     pm2 delete default
#     pm2 start -f /home/ubuntu/udapeople/backend/dist/main.js