- name: Copy backend
  become: yes
  copy:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/udapeople/
    owner: ubuntu
    mode: 0644
- name: Extract Backend
  become: yes
  shell: |
    cd /home/ubuntu/udapeople
    tar -xf artifact.tar.gz
    ls
- name: Start server
  become: yes
  shell: |
    pm2 delete all
    pm2 start npm --name "udapeople-backend" -- start