- name: Copy backend
  become: yes
  copy:
    src: ../../backend/dist
    dest: /home/ubuntu/udapeople
- name: Copy node_modules
  become: yes
  copy:
    src: ../../backend/node_modules
    dest: /home/ubuntu/udapeople
- name: Start server
  shell: |
    pm2 delete all
    pm2 start -f /home/ubuntu/udapeople/main.js