- name: Copy backend
  become: yes
  copy:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/udapeople
- name: Extract Backend
  shell: |
    apt install tar gzip
    cd /home/ubuntu/udapeople
    tar -xf backend.tar.gz
    ls
- name: Start server
  shell: |
    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    pm2 delete default
    pm2 start -f /home/ubuntu/udapeople/backend/dist/main.js