- name: Copy backend
  become: yes
  synchronize:
    src: ../../backend/dist
    dest: /home/ubuntu/udapeople
    recursive: true
- name: Copy node_modules
  become: yes
  synchronize:
    src: ../../backend/node_modules
    dest: /home/ubuntu/udapeople
    recursive: true